version: '3'

services:
  database:
    image: postgres:10.3-alpine
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=tswdatabase
      - POSTGRES_PASSWORD=tswdatabase
      - POSTGRES_DB=tswdatabase
